Bancdeltemps:
    type: entity
    table: bancdeltemps
    uniqueConstraints:
        nom_UNIQUE:
            columns:
                - nom
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        saldoMinim:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: saldo_minim
        tempsInactivitat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: temps_inactivitat
    lifecycleCallbacks: {  }
