Evaluacioservei:
    type: entity
    table: EvaluacioServei
    indexes:
        fk_usuari_has_serveis_serveis2:
            columns:
                - serveis_id
                - serveis_tipus_servei_id
                - serveis_estat_servei_id
        fk_usuari_has_serveis_usuari2:
            columns:
                - usuari_id
        IDX_C2BD0F3DA55C797F:
            columns:
                - serveis_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        serveisTipusServeiId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: serveis_tipus_servei_id
        serveisEstatServeiId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: serveis_estat_servei_id
        valoracioservei:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: valoracioServei
        comentari:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: Comentari
    manyToOne:
        usuari:
            targetEntity: Usuari
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuari_id:
                    referencedColumnName: id
            orphanRemoval: false
        serveis:
            targetEntity: Serveis
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                serveis_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
