Missatges:
    type: entity
    table: missatges
    indexes:
        fk_missatges_Solicituts1:
            columns:
                - Solicituts_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        missatge:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        data:
            type: date
            nullable: false
            comment: ''
        autor:
            type: string
            nullable: false
            length: 55
            fixed: false
            comment: ''
    manyToOne:
        solicituts:
            targetEntity: Solicituts
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Solicituts_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
