Persona:
    type: entity
    table: Persona
    indexes:
        fk_Persona_rol1:
            columns:
                - rol_user_role
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        salt:
            type: string
            nullable: true
            length: 40
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 75
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
    manyToOne:
        rolUserRole:
            targetEntity: Rol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_user_role:
                    referencedColumnName: user_role
            orphanRemoval: false
    lifecycleCallbacks: {  }
