Rol:
    type: entity
    table: rol
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userRole:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: user_role
    lifecycleCallbacks: {  }
