Serveisconsumits:
    type: entity
    table: serveisconsumits
    indexes:
        fk_idservei_oferit:
            columns:
                - idServei
        fk_serveisconsumits_valoracio_servei1:
            columns:
                - valoracio_servei_id
        fk_idusuari_consumidor:
            columns:
                - idUsuari
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        comentaris:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        idservei:
            targetEntity: Serveis
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idServei:
                    referencedColumnName: id
            orphanRemoval: false
        idusuari:
            targetEntity: Usuari
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idUsuari:
                    referencedColumnName: id
            orphanRemoval: false
        valoracioServei:
            targetEntity: ValoracioServei
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                valoracio_servei_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
