Serveisoferts:
    type: entity
    table: serveisoferts
    indexes:
        fk_idservei_ofert:
            columns:
                - idServei
        fk_idusuari_solicitant:
            columns:
                - idUsuari
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idservei:
            targetEntity: Serveis
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idServei:
                    referencedColumnName: id
            orphanRemoval: false
        idusuari:
            targetEntity: Usuari
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idUsuari:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
