Solicituts:
    type: entity
    table: Solicituts
    indexes:
        fk_usuari_has_serveis_usuari1:
            columns:
                - solicitant_id
        fk_Solicituts_serveis1:
            columns:
                - servei_solicitat_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estatsolicitut:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: estatSolicitut
    manyToOne:
        solicitant:
            targetEntity: Usuari
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                solicitant_id:
                    referencedColumnName: id
            orphanRemoval: false
        serveiSolicitat:
            targetEntity: Serveis
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                servei_solicitat_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
