TipusServei:
    type: entity
    table: tipus_servei
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 55
            fixed: false
            comment: ''
        descripcio:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
