Usuari:
    type: entity
    table: usuari
    indexes:
        fk_usuari_grup1:
            columns:
                - grup_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 55
            fixed: false
            comment: ''
        cognom:
            type: string
            nullable: false
            length: 55
            fixed: false
            comment: ''
    manyToOne:
        grup:
            targetEntity: Grup
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                grup_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
