Usuari:
    type: entity
    table: usuari
    indexes:
        fk_usuari_Persona1:
            columns:
                - Persona_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 55
            fixed: false
            comment: ''
        cognom:
            type: string
            nullable: false
            length: 55
            fixed: false
            comment: ''
        adreca:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        telefon:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
        fotografia:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        presentacio:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        punts:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    manyToOne:
        persona:
            targetEntity: Persona
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Persona_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
