ValoracioServei:
    type: entity
    table: valoracio_servei
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
