<?php

namespace Proxies\__CG__\bonavall\BancdeltempsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Serveis extends \bonavall\BancdeltempsBundle\Entity\Serveis implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'iddonant', 'punts', 'nomServei', 'descripcioServei', 'poblacio', 'dataInici', 'durada', 'dataFinal', 'tipusServei1', 'estatServei');
        }

        return array('__isInitialized__', 'id', 'iddonant', 'punts', 'nomServei', 'descripcioServei', 'poblacio', 'dataInici', 'durada', 'dataFinal', 'tipusServei1', 'estatServei');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Serveis $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomServei()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomServei', array());

        return parent::getNomServei();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomServei($nomServei)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomServei', array($nomServei));

        return parent::setNomServei($nomServei);
    }

    /**
     * {@inheritDoc}
     */
    public function setIddonant($iddonant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIddonant', array($iddonant));

        return parent::setIddonant($iddonant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIddonant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIddonant', array());

        return parent::getIddonant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPunts($punts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPunts', array($punts));

        return parent::setPunts($punts);
    }

    /**
     * {@inheritDoc}
     */
    public function getPunts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPunts', array());

        return parent::getPunts();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcioServei()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcioServei', array());

        return parent::getDescripcioServei();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcioServei($descripcioServei)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcioServei', array($descripcioServei));

        return parent::setDescripcioServei($descripcioServei);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInici($dataInici)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInici', array($dataInici));

        return parent::setDataInici($dataInici);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInici()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInici', array());

        return parent::getDataInici();
    }

    /**
     * {@inheritDoc}
     */
    public function getPoblacio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoblacio', array());

        return parent::getPoblacio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoblacio($poblacio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoblacio', array($poblacio));

        return parent::setPoblacio($poblacio);
    }

    /**
     * {@inheritDoc}
     */
    public function setDurada($durada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDurada', array($durada));

        return parent::setDurada($durada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDurada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDurada', array());

        return parent::getDurada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFinal($dataFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFinal', array($dataFinal));

        return parent::setDataFinal($dataFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFinal', array());

        return parent::getDataFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipusServei1(\bonavall\BancdeltempsBundle\Entity\TipusServei $tipusServei1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipusServei1', array($tipusServei1));

        return parent::setTipusServei1($tipusServei1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipusServei1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipusServei1', array());

        return parent::getTipusServei1();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstatServei(\bonavall\BancdeltempsBundle\Entity\EstatServei $estatServei = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstatServei', array($estatServei));

        return parent::setEstatServei($estatServei);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstatServei()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstatServei', array());

        return parent::getEstatServei();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
