<?php

namespace Proxies\__CG__\bonavall\BancdeltempsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Solicituts extends \bonavall\BancdeltempsBundle\Entity\Solicituts implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'solicitant', 'serveiSolicitat', 'dataSolicitut', 'estatSolicitut');
        }

        return array('__isInitialized__', 'id', 'solicitant', 'serveiSolicitat', 'dataSolicitut', 'estatSolicitut');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Solicituts $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstatsolicitut(\bonavall\BancdeltempsBundle\Entity\EstatServei $estatServei = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstatsolicitut', array($estatServei));

        return parent::setEstatsolicitut($estatServei);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstatsolicitut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstatsolicitut', array());

        return parent::getEstatsolicitut();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitant(\bonavall\BancdeltempsBundle\Entity\Persona $solicitant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitant', array($solicitant));

        return parent::setSolicitant($solicitant);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitant', array());

        return parent::getSolicitant();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfertant(\bonavall\BancdeltempsBundle\Entity\Persona $ofertant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfertant', array($ofertant));

        return parent::setOfertant($ofertant);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfertant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfertant', array());

        return parent::getOfertant();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataSolicitut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataSolicitut', array());

        return parent::getDataSolicitut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataSolicitut(\DateTime $dataSolicitut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataSolicitut', array($dataSolicitut));

        return parent::setDataSolicitut($dataSolicitut);
    }

    /**
     * {@inheritDoc}
     */
    public function setServeiSolicitat(\bonavall\BancdeltempsBundle\Entity\Serveis $serveiSolicitat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServeiSolicitat', array($serveiSolicitat));

        return parent::setServeiSolicitat($serveiSolicitat);
    }

    /**
     * {@inheritDoc}
     */
    public function getServeiSolicitat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServeiSolicitat', array());

        return parent::getServeiSolicitat();
    }

}
