security:
    encoders:
        bonavall\BancdeltempsBundle\Entity\Persona: plaintext
            #algorithm: sha512
            #encode-as-base64: true
            #iterations: 10
 
#    role_hierarchy:
#        ROLE_USER: [ROLE_USER]
 
    providers:
        usuaris:
            entity: { class: bonavall\BancdeltempsBundle\Entity\Usuari, property: email }
            entity: { class: bonavall\BancdeltempsBundle\Entity\Persona, property: email }
        
        in_memory:
          memory:
              users:
                  ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                  admin: { password: kitten, roles: 'ROLE_ADMIN' }
 
    firewalls:
        main:
            pattern: /.*
            provider: usuaris
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: sessionCookie
                lifetime: 1800
                path: /.*
                domain: ~
            security: ~
            anonymous: ~
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
