bonavall_bancdeltemps_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: bonavallBancdeltempsBundle:Default:index }
    
bonavall_bancdeltemps_inici:
    pattern:  /
    defaults: { _controller: bonavallBancdeltempsBundle:Default:inici }
    
bonavall_bancdeltemps_user:
    pattern:  /user
    defaults: { _controller: bonavallBancdeltempsBundle:Default:user }
    
logout:
    pattern: /logout
    
login:
    pattern:   /login
    defaults:  { _controller: bonavallBancdeltempsBundle:Security:login }
    
login_check:
    pattern:   /login_check
