bonavall_bancdeltemps_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: bonavallBancdeltempsBundle:Default:index }
    
bonavall_bancdeltemps_inici:
    pattern:  /
    defaults: { _controller: bonavallBancdeltempsBundle:Default:inici }
    
bonavall_bancdeltemps_login:
    pattern: /login
    defaults: { _controller: bonavallBancdeltempsBundle:Security:login }
 
bonavall_bancdeltemps_login_check:
    pattern: /login_check
 
bonavall_bancdeltemps_logout:
    pattern: /logout
    
