#Rutes inicials
bonavall_bancdeltemps_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: bonavallBancdeltempsBundle:Default:index }

bonavall_bancdeltemps_inici:
    pattern:  /
    defaults: { _controller: bonavallBancdeltempsBundle:Default:index }

bonavall_bancdeltemps_alta:
    pattern:  /alta
    defaults: { _controller: bonavallBancdeltempsBundle:Registre:index }

### Prova nova alta usuari
bonavall_bancdeltemps_altausuari:
    pattern:  /altausuari/
    defaults: { _controller: bonavallBancdeltempsBundle:AltaUsuari:registre }
### Final Prova


bonavall_bancdeltemps_user:
    pattern:  /user
    defaults: { _controller: bonavallBancdeltempsBundle:Default:user }
    
bonavall_bancdeltemps_admin:
    pattern:  /admin/
    defaults: { _controller: bonavallBancdeltempsBundle:Default:admin }
    
logout:
    pattern: /logout
    
login:
    pattern:   /login
    defaults:  { _controller: bonavallBancdeltempsBundle:Security:login }
    
login_check:
    pattern:   /login_check

#Rutes Administrador
persona:
  pattern: /admin/persona/
  defaults: { _controller: bonavallBancdeltempsBundle:Persona:index }
persona_create:
  pattern: /admin/persona/create
  defaults: { _controller: bonavallBancdeltempsBundle:Persona:create }
persona_update:
  pattern: /admin/persona/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Persona:update }
persona_show:
  pattern: /admin/persona/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Persona:show }
persona_edit:
  pattern: /admin/persona/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Persona:edit }
persona_new:
  pattern: /admin/persona/new
  defaults: { _controller: bonavallBancdeltempsBundle:Persona:new }
persona_delete:
  pattern: /admin/persona/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Persona:delete }


usuari:
  pattern: /admin/usuari/
  defaults: { _controller: bonavallBancdeltempsBundle:Usuari:index }
usuari_create:
  pattern: /admin/usuari/create
  defaults: { _controller: bonavallBancdeltempsBundle:Usuari:create }
usuari_update:
  pattern: /admin/usuari/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Usuari:update }
usuari_show:
  pattern: /admin/usuari/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Usuari:show }
usuari_edit:
  pattern: /admin/usuari/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Usuari:edit }
usuari_new:
  pattern: /admin/usuari/new
  defaults: { _controller: bonavallBancdeltempsBundle:Usuari:new }
usuari_delete:
  pattern: /admin/usuari/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Usuari:delete }


Admin_bancdeltemps:
  pattern: /admin/bancdeltemps/
  defaults: { _controller: bonavallBancdeltempsBundle:Bancdeltemps:index }
Admin_bancdeltemps_create:
  pattern: /admin/bancdeltemps/create
  defaults: { _controller: bonavallBancdeltempsBundle:Bancdeltemps:create }
Admin_bancdeltemps_update:
  pattern: /admin/bancdeltemps/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Bancdeltemps:update }
Admin_bancdeltemps_show:
  pattern: /admin/bancdeltemps/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Bancdeltemps:show }
Admin_bancdeltemps_edit:
  pattern: /admin/bancdeltemps/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Bancdeltemps:edit }
Admin_bancdeltemps_new:
  pattern: /admin/bancdeltemps/new
  defaults: { _controller: bonavallBancdeltempsBundle:Bancdeltemps:new }
Admin_bancdeltemps_delete:
  pattern: /admin/bancdeltemps/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Bancdeltemps:delete }
  
  
admin_serveis:
  pattern: /admin/serveis/
  defaults: { _controller: bonavallBancdeltempsBundle:Serveis:index }
admin_serveis_create:
  pattern: /admin/serveis/create
  defaults: { _controller: bonavallBancdeltempsBundle:Serveis:create }
admin_serveis_update:
  pattern: /admin/serveis/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Serveis:update }
admin_serveis_show:
  pattern: /admin/serveis/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Serveis:show }
admin_serveis_edit:
  pattern: /admin/serveis/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Serveis:edit }
admin_serveis_new:
  pattern: /admin/serveis/new
  defaults: { _controller: bonavallBancdeltempsBundle:Serveis:new }
admin_serveis_delete:
  pattern: /admin/serveis/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Serveis:delete }
  
  
admin_tipusservei:
  pattern: /admin/tipusservei/
  defaults: { _controller: bonavallBancdeltempsBundle:TipusServei:index }
admin_tipusservei_create:
  pattern: /admin/tipusservei/create
  defaults: { _controller: bonavallBancdeltempsBundle:TipusServei:create }
admin_tipusservei_update:
  pattern: /admin/tipusservei/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:TipusServei:update }
admin_tipusservei_show:
  pattern: /admin/tipusservei/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:TipusServei:show }
admin_tipusservei_edit:
  pattern: /admin/tipusservei/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:TipusServei:edit }
admin_tipusservei_new:
  pattern: /admin/tipusservei/new
  defaults: { _controller: bonavallBancdeltempsBundle:TipusServei:new }
admin_tipusservei_delete:
  pattern: /admin/tipusservei/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:TipusServei:delete }
  
  
admin_estatservei:
  pattern: /admin/estatservei/
  defaults: { _controller: bonavallBancdeltempsBundle:EstatServei:index }
admin_estatservei_create:
  pattern: /admin/estatservei/create
  defaults: { _controller: bonavallBancdeltempsBundle:EstatServei:create }
admin_estatservei_update:
  pattern: /admin/estatservei/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:EstatServei:update }
admin_estatservei_show:
  pattern: /admin/estatservei/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:EstatServei:show }
admin_estatservei_edit:
  pattern: /admin/estatservei/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:EstatServei:edit }
admin_estatservei_new:
  pattern: /admin/estatservei/new
  defaults: { _controller: bonavallBancdeltempsBundle:EstatServei:new }
admin_estatservei_delete:
  pattern: /admin/estatservei/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:EstatServei:delete }
  
  
admin_serveisconsumits:
  pattern: /admin/serveisconsumits/
  defaults: { _controller: bonavallBancdeltempsBundle:Serveisconsumits:index }
admin_serveisconsumits_create:
  pattern: /admin/serveisconsumits/create
  defaults: { _controller: bonavallBancdeltempsBundle:Serveisconsumits:create }
admin_serveisconsumits_update:
  pattern: /admin/serveisconsumits/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Serveisconsumits:update }
admin_serveisconsumits_show:
  pattern: /admin/serveisconsumits/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Serveisconsumits:show }
admin_serveisconsumits_edit:
  pattern: /admin/serveisconsumits/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Serveisconsumits:edit }
admin_serveisconsumits_new:
  pattern: /admin/serveisconsumits/new
  defaults: { _controller: bonavallBancdeltempsBundle:Serveisconsumits:new }
admin_serveisconsumits_delete:
  pattern: /admin/serveisconsumits/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Serveisconsumits:delete }
  
  
admin_valoracioservei:
  pattern: /admin/valoracioservei/
  defaults: { _controller: bonavallBancdeltempsBundle:ValoracioServei:index }
admin_valoracioservei_create:
  pattern: /admin/valoracioservei/create
  defaults: { _controller: bonavallBancdeltempsBundle:ValoracioServei:create }
admin_valoracioservei_update:
  pattern: /admin/valoracioservei/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:ValoracioServei:update }
admin_valoracioservei_show:
  pattern: /admin/valoracioservei/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:ValoracioServei:show }
admin_valoracioservei_edit:
  pattern: /admin/valoracioservei/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:ValoracioServei:edit }
admin_valoracioservei_new:
  pattern: /admin/valoracioservei/new
  defaults: { _controller: bonavallBancdeltempsBundle:ValoracioServei:new }
admin_valoracioservei_delete:
  pattern: /admin/valoracioservei/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:ValoracioServei:delete }

  
admin_evaluacioservei:
  pattern: /admin/evaluacioservei/
  defaults: { _controller: bonavallBancdeltempsBundle:Evaluacioservei:index }
admin_evaluacioservei_create:
  pattern: /admin/evaluacioservei/create
  defaults: { _controller: bonavallBancdeltempsBundle:Evaluacioservei:create }
admin_evaluacioservei_update:
  pattern: /admin/evaluacioservei/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Evaluacioservei:update }
admin_evaluacioservei_show:
  pattern: /admin/evaluacioservei/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Evaluacioservei:show }
admin_evaluacioservei_edit:
  pattern: /admin/evaluacioservei/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Evaluacioservei:edit }
admin_evaluacioservei_new:
  pattern: /admin/evaluacioservei/new
  defaults: { _controller: bonavallBancdeltempsBundle:Evaluacioservei:new }
admin_evaluacioservei_delete:
  pattern: /admin/evaluacioservei/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Evaluacioservei:delete }
  
  
admin_solicituts:
  pattern: /admin/solicituts/
  defaults: { _controller: bonavallBancdeltempsBundle:Solicituts:index }
admin_solicituts_create:
  pattern: /admin/solicituts/create
  defaults: { _controller: bonavallBancdeltempsBundle:Solicituts:create }
admin_solicituts_update:
  pattern: /admin/solicituts/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Solicituts:update }
admin_solicituts_show:
  pattern: /admin/solicituts/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Solicituts:show }
admin_solicituts_edit:
  pattern: /admin/solicituts/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Solicituts:edit }
admin_solicituts_new:
  pattern: /admin/solicituts/new
  defaults: { _controller: bonavallBancdeltempsBundle:Solicituts:new }
admin_solicituts_delete:
  pattern: /admin/solicituts/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Solicituts:delete }  

  
admin_missatges:
  pattern: /admin/missatges/
  defaults: { _controller: bonavallBancdeltempsBundle:Missatges:index }
admin_missatges_create:
  pattern: /admin/missatges/create
  defaults: { _controller: bonavallBancdeltempsBundle:Missatges:create }
admin_missatges_update:
  pattern: /admin/missatges/update{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Missatges:update }
admin_missatges_show:
  pattern: /admin/missatges/show{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Missatges:show }
admin_missatges_edit:
  pattern: /admin/missatges/edit{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Missatges:edit }
admin_missatges_new:
  pattern: /admin/missatges/new
  defaults: { _controller: bonavallBancdeltempsBundle:Missatges:new }
admin_missatges_delete:
  pattern: /admin/missatges/delete{id}
  defaults: { _controller: bonavallBancdeltempsBundle:Missatges:delete }    
  
user_miss:
    pattern: /missatges/
    defaults: { _controller: bonavallBancdeltempsBundle:UserMiss:index }


missatges_ajax:
      pattern: /user/solicituts/
      defaults: { _controller: bonavallBancdeltempsBundle:UserMiss:greeting }
      requirements:
        _method:  POST
  


#Rutes de user no administrador
perfil_user:
  pattern: /user/perfil/
  defaults: { _controller: bonavallBancdeltempsBundle:Usuari:perfil }
gestio_solicituds_enviades:
  pattern: /user/solicituts/enviades/
  defaults: { _controller: bonavallBancdeltempsBundle:UserSolicituts:enviades }
gestio_solicituds_rebudes:
  pattern: /user/solicituts/rebudes/
  defaults: { _controller: bonavallBancdeltempsBundle:UserSolicituts:rebudes }
gestio_serveis:
  pattern: /user/serveis/
  defaults: { _controller: bonavallBancdeltempsBundle:Serveis:index }

