bonavall\Bancdeltemps\Entity\Persona:
    properties:
        email:
          - NotBlank:  { message: "persona.email.not_blank" }
        password:
          - NotBlank: { message: "persona.password.not_blank" }
          